package com.marksem.entity.booking;

public enum BookingMaintenanceType {
    RESTAURANT_TABLE_RESERVATION,
    TRANSFER_AND_TAXI,
    FIREWOOD_FOR_BARBECUE,
    ORGANIZATION_OF_FISHING,
    FOOD_DELIVERY,
    BIKE_ROLLERS_SCOOTER_DELIVERY,
    CALL_THE_CLEANER,
    EXCURSION_BOOKING,
    SUN_LOUNGER_BOOKING,
    FLOWER_DELIVERY,
    BABYSITTING_ORDER,
    OTHER;
}
