spring:
  profiles: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: danitfinalfs11
    password: danit__finalfs11
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        web-allow-others: true

jwt:
  secret: proselyt4
  secretRefresh: 7xfn849ff
  secretPasswordReset: oo9ii7gg4
  secretPasswordUpdate: dd955l3mm
  expiration: 7200
  expirationRefresh: 604800
  expirationPasswordReset: 86400
  expirationPasswordUpdate: 3600
  header: Authorization

url:
  server: http://localhost:8080
  client: http://localhost:3000
  fileServer: http://localhost:8090

clientChangePasswordPath: changePassword
serverChangePasswordPath: api/v1/auth/resetPassword