spring:
  profiles:
    active: prod
---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://ec2-52-205-145-201.compute-1.amazonaws.com:5432/dfbohplvljtqie
    driver-class-name: org.postgresql.Driver
    username: mlpeugyvcdinfn
    password: e1a1ff54ded8c5b22e835e7b0c616d43db806e72a3d1f1344f04c8c6cda82c72
    initialization-mode: never
#    data: classpath:sql/data.sql


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:?SET_ENVIOMENT_MAIL_USERNAME_IN_SYSTEM}
    password: ${MAIL_PASSWORD:?SET_ENVIOMENT_MAIL_USERNAME_IN_SYSTEM}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000
          starttls:
            enable: true
springdoc:
  swagger-ui:
    path: /doc
url:
  server: ${SERVER_URL:?SET_ENVIOMENT_SERVER_URL_IN_SYSTEM}
  client: ${CLIENT_URL:?SET_ENVIOMENT_CLIENT_URL_IN_SYSTEM}
---
spring:
  profiles: my
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:
        data:
          classpath: sql/data.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        web-allow-others: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: 85Ej2vMDrqcTq6u
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000
          starttls:
            enable: true
---
jwt:
  secret: proselyt4
  secretRefresh: 7xfn849ff
  secretPasswordReset: oo9ii7gg4
  secretPasswordUpdate: dd955l3mm
  expiration: 7200
  expirationRefresh: 604800
  expirationPasswordReset: 86400
  expirationPasswordUpdate: 3600
  header: Authorization

