spring:
  profiles: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:?SET_ENVIOMENT_MAIL_USERNAME_IN_SYSTEM}
    password: ${MAIL_PASSWORD:?SET_ENVIOMENT_MAIL_USERNAME_IN_SYSTEM}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000
          starttls:
            enable: true
  datasource:
    url: ${DATA_BASE_URL:?SET_ENVIOMENT_DATA_BASE_URL_IN_SYSTEM}
    driver-class-name: org.postgresql.Driver
    username: ${DATA_BASE_USERNAME:?SET_ENVIOMENT_DATA_BASE_USERNAME_URL_IN_SYSTEM}
    password: ${DATA_BASE_PASSWORD:?SET_ENVIOMENT_DATA_BASE_PASSWORD_URL_IN_SYSTEM}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  header: Authorization
  secret: ${JWT_SECRET:?SET_ENVIOMENT_DJWT_SECRET_IN_SYSTEM}
  secretRefresh: ${JWT_SECRET_EMAIL:?SET_ENVIOMENT_JWT_SECRET_REFRESH_IN_SYSTEM}
  secretPasswordReset: ${JWT_SECRET_EMAIL:?SET_ENVIOMENT_JWT_SECRET_PASWORD_RESET_IN_SYSTEM}
  secretPasswordUpdate: ${JWT_SECRET_EMAIL:?SET_ENVIOMENT_JWT_SECRET_PASWORD_UPDATE_IN_SYSTEM}
  expiration: 7200
  expirationRefresh: 604800
  expirationPasswordReset: 86400
  expirationPasswordUpdate: 3600
url:
  server: ${SERVER_URL:?SET_ENVIOMENT_SERVER_URL_IN_SYSTEM}
  client: ${CLIENT_URL:?SET_ENVIOMENT_CLIENT_URL_IN_SYSTEM}

clientChangePasswordPath: changePassword
serverChangePasswordPath: api/v1/auth/resetPassword