spring:
  profiles: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: danitfinalfs11
    password: danit__finalfs11
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000
          starttls:
            enable: true
    datasource:
      password: 493077dc5026b18df4824079d0f6b5edcbd90e1412d78740ee4efcbf33a33786
      url: jdbc:postgresql://ec2-34-203-155-237.compute-1.amazonaws.com:5432/d5hesr0m3s24i2
      username: bdstuhtppfwzdl
      initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
jwt:
  secret: proselyt4
  secretRefresh: 7xfn849ff
  secretPasswordReset: oo9ii7gg4
  secretPasswordUpdate: dd955l3mm
  expiration: 7200
  expirationRefresh: 604800
  expirationPasswordReset: 86400
  expirationPasswordUpdate: 3600
  header: Authorization
url:
  server: http://localhost:8080
  client: http://localhost:3000
  fileServer: http://165.232.150.188:8090
clientChangePasswordPath: changePassword
serverChangePasswordPath: api/v1/auth/resetPassword
